### ISSUE TITLE
Correct way to implement on @NgModule?

### ISSUE THREAD

**Issue by cport1** [ngrx/router-store#22]
I keep getting this error after attempting to implement ngrx/router-store::

TypeError: Cannot read property 'call' of undefined
    at getLatestUrl (http://localhost:4200/main.bundle.js:66075:79)
    at connectRouterActions (http://localhost:4200/main.bundle.js:66079:109)
    at http://localhost:4200/main.bundle.js:66142:102
    at Array.forEach (native)
    at ApplicationRef_._loadComponent (http://localhost:4200/main.bundle.js:27900:19)
    at ApplicationRef_.bootstrap (http://localhost:4200/main.bundle.js:27886:14)
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (http://localhost:4200/main.bundle.js:27788:42)
    at http://localhost:4200/main.bundle.js:27756:27

app.module.ts:::

```
import { StoreModule } from '@ngrx/store';
import { StoreDevtoolsModule } from '@ngrx/store-devtools';
import { StoreLogMonitorModule, useLogMonitor } from '@ngrx/store-log-monitor';
import { RouterStoreModule, routerReducer } from "@ngrx/router-store";
import actions from './actions';
import reducer from './reducers';
import effects from './effects';
import { runEffects } from '@ngrx/effects';
@NgModule({
imports: [
    StoreModule.provideStore({ reducer, router: routerReducer }),
    StoreDevtoolsModule.instrumentStore({
      monitor: useLogMonitor({
        visible: false,
        position: 'right'
      })
    }),
    StoreLogMonitorModule,
    RouterStoreModule.connectRouter()
]
})
```

reducers/index.ts:::

```
import '@ngrx/core/add/operator/select';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/let';
import { Observable } from 'rxjs/Observable';
import { compose } from '@ngrx/core/compose';
import { storeLogger } from 'ngrx-store-logger';
import { storeFreeze } from 'ngrx-store-freeze';
import { combineReducers } from '@ngrx/store';
import { RouterState, routerReducer } from '@ngrx/router-store';
import { UserState, UserReducer } from './UserReducer';
import { ReportState, ReportReducer } from "./CurrentReportReducer";

export * from './UserReducer';

export interface AppState {
  user: UserState,
  currentReport: ReportState,
  router: RouterState
}

export default compose(storeFreeze, storeLogger(), combineReducers)({
  user: UserReducer,
  report: ReportReducer,
  router: routerReducer
});

```

Package.json:: 

```
"dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@ngrx/core": "^1.1.0",
    "@ngrx/effects": "^1.0.1",
    "@ngrx/router-store": "^1.2.2",
    "@ngrx/store": "^2.1.2",
    "@ngrx/store-devtools": "^3.0.1",
    "@ngrx/store-log-monitor": "^3.0.1",
    "angular-cli": "^1.0.0-beta.11-webpack.8",
    "angular2-jwt": "^0.1.19",
    "core-js": "^2.4.1",
    "ng-semantic": "^1.1.11",
    "ng2-datepicker": "^0.8.0",
    "ngrx-store-freeze": "^0.1.0",
    "ngrx-store-logger": "^0.1.7",
    "reflect-metadata": "0.1.3",
    "reselect": "^2.5.3",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/protractor": "^1.5.16",
    "angular-cli": "^1.0.0-beta.11-webpack.8",
    "awesome-typescript-loader": "^2.2.3",
    "codelyzer": "0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-coverage": "^1.0.0",
    "karma-jasmine": "0.3.8",
    "node-sass": "^3.8.0",
    "protractor": "3.3.0",
    "raw-loader": "^0.5.1",
    "sass-loader": "^4.0.0",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
```

**Comment by ritz078** [comment]
In `app.module.ts`, change `StoreModule.provideStore({ reducer, router: routerReducer })` to `StoreModule.provideStore(reducer)`

**Comment by brandonroberts** [comment]
Thanks

**Comment by cport1** [comment]
still getting the same error

**Comment by brandonroberts** [comment]
Did you install `"@ngrx/core": "^1.2.0"`?

**Comment by cport1** [comment]
That resolved my issue above, but now I am getting the same error as  https://github.com/ngrx/router-store/issues/21
